tuned the dev setup script

diff --git a/dev-setup b/dev-setup
--- a/dev-setup
+++ b/dev-setup
@@ -1,9 +1,12 @@
 #!/bin/sh
 
 set -e
-pblue="\033[0;34m"
-pgreen="\033[0;32m"
-preset="\033[0m"
+set -o errexit
+set -o nounset
+
+readonly pblue="\033[0;34m"
+readonly pgreen="\033[0;32m"
+readonly preset="\033[0m"
 
 PWD=`pwd`
 
@@ -16,13 +19,19 @@ echo "${pgreen}\_| \_/\__,_|\___/|_| |_|\__,_|${preset}"
 echo
 echo "${pblue}Kuona developer setup${preset} for ${pgreen}${PWD}${preset}"
 
-if ! command -v grunt >/dev/null 2>&1; then
+if command -v brew >/dev/null 2>&1; then
     echo "${pblue}Installing required tools using hombrew and bundle${preset}"
     brew bundle
 fi
 
+
+if ! command -v grunt >/dev/null 2>&1; then
+    echo "${pblue}Installing required tools using hombrew and bundle${preset}"
+    npm install -g grunt-cli
+fi
+
 echo "${pblue}Setting up web development environment${preset}"
-cd dashboard; sh dev-setup; cd ..
+cd dashboard; npm install; cd ..
 
 LOG_PATH=/var/log/kuona
 
