Colorizing dev setup script

diff --git a/dev-setup b/dev-setup
--- a/dev-setup
+++ b/dev-setup
@@ -1,25 +1,31 @@
-echo "Kuona developer setup"
+#!/bin/sh
 
-echo Initialising sub-modules
+set -e
+pblue="\033[0;34m"
+pgreen="\033[0;32m"
+preset="\033[0m"
 
+echo "${pblue}Kuona developer setup${preset}"
+
+echo "${pblue}Initialising sub-modules${preset}"
 git submodule init
 
-echo Updating repositories
+echo "${pblue}Updating repositories${preset}"
 
 git submodule update
 
-echo Module status
+echo "${pblue}Module status${preset}"
 
 git submodule status
 
-echo Installing required tool using hombrew and bundle
+echo "${pblue}Installing required tool using hombrew and bundle${preset}"
 
 brew bundle
-
 cd dashboard; sh dev-setup; cd ..
 
-echo Initial environment service setup
+echo "${pblue}Initial environment service setup${preset}"
 
 cd environment-service; lein deps
-
 cd ../git-collector;lein deps
+
+echo "${pgreen}Ready to develop! Start with the readme.${preset}"
